name: key_manage
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.2.5  # add dependency for Firebase Core

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.6.6
  firebase_database: ^1.0.5

  # The following adds QR code capabilities to the application.
  # More information from:
  # https://medium.com/flutter-community/building-flutter-qr-code-generator-scanner-and-sharing-app-703e73b228d3
  path_provider: 1.1.0
  barcode_scan: 1.0.0
  qr_flutter: 2.0.0+51

  # The follow allows the formatting for dates.
  intl: ^0.15.8

  # To enable firestore queries
  # cloud_firestore: 0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Plugin for app launcher icons to be made from icons.
  # More information from:
  # https://stackoverflow.com/questions/43928702/how-to-change-the-application-launcher-icon-on-flutter
  flutter_launcher_icons: ^0.6.1

dependency_overrides:
  image: 2.0.7

# Specifies for app launcher icon to be made from image path.
# The made icon is used for both android and ios.
flutter_icons:
  android: true
  ios: true
  image_path: "assets/key_with_background.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
